---
- name: "create directory udapeople-appfiles"
  file:
    path: /home/ubuntu/udapeople-appfiles
    state: directory
    mode: "0777"

- name: "copy nodejs app to backend-server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople-artifact.tar.gz

- name: "unarchive nodejs app on backend-server"
  unarchive:
    src: /home/ubuntu/udapeople-artifact.tar.gz
    dest: /home/ubuntu/udapeople-appfiles/
    remote_src: yes

- name: "copy dotenv file to backend-server"
  copy:
    src: /home/ubuntu/udapeople-appfiles/.env
    dest: /home/ubuntu/udapeople-appfiles/dist/.env
    remote_src: yes

- name: "start the backend app-stage 1"
  become: true
  command:
    chdir: /home/ubuntu/udapeople-appfiles/dist
    cmd: npm install
    cmd: pm2 stop default
    cmd: pm2 start main.js
# - name: "start the backend app-stage 2"
#   become: true
#   command: pm2 start npm -- start
#   args:
#     chdir: /home/ubuntu/udapeople-appfiles/dist/
# environment:
#   ENVIRONMENT: "production"
#   TYPEORM_MIGRATIONS_DIR: "./migrations"
#   TYPEORM_ENTITIES: "./modules/domain/**/*.entity.js"
#   TYPEORM_MIGRATIONS: "./migrations/*.js"
#   TYPEORM_PORT: 5432
#   TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
#   TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
#   TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
#   TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
#   TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
