---
- name: "create directory udapeople-appfiles"
  file:
    path: /home/ubuntu/udapeople-appfiles
    state: directory
    mode: "600"

- name: "copy nodejs app to backend-server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople-artifact.tar.gz

- name: "unarchive nodejs app on backend-server"
  unarchive:
    src: /home/ubuntu/udapeople-artifact.tar.gz
    dest: /home/ubuntu/udapeople-appfiles/
    remote_src: yes

- name: "start the backend app-stage 1"
  become: true
  shell: npm install
  pm2 stop default

- name: "start the backend app-stage 2"
  become: true
  command: pm2 start main.js
  args:
    chdir: /home/ubuntu/udapeople-appfiles/dist/
  environment:
    NODE_ENV: production
    VERSION: 1
    TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
    TYPEORM_MIGRATIONS_DIR: "{{ lookup('env', 'TYPEORM_MIGRATIONS_DIR') }}"
    TYPEORM_ENTITIES: "{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    TYPEORM_MIGRATIONS: "{{ lookup('env', 'TYPEORM_MIGRATIONS') }}"
    TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"
    TYPEORM_PORT: 5432
    TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
    TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
    TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
