---
- name: "create directory udapeople-appfiles"
  file:
    path: /home/ubuntu/udapeople-appfiles
    state: directory
    mode: "0777"

- name: "copy nodejs app to backend-server"
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/udapeople-artifact.tar.gz

- name: "unarchive nodejs app on backend-server"
  unarchive:
    src: /home/ubuntu/udapeople-artifact.tar.gz
    dest: /home/ubuntu/udapeople-appfiles/
    remote_src: yes

- name: "copy dotenv file to backend-server"
  copy:
    src: /home/ubuntu/udapeople-appfiles/.env
    dest: /home/ubuntu/udapeople-appfiles/dist/.env
    remote_src: yes

- name: "start the backend app-stage 1"
  become: true
  command:
    chdir: /home/ubuntu/udapeople-appfiles/
    cmd: npm install

- name: "start the backend app-stage 2"
  become: true
  shell: |
    cd /home/ubuntu/udapeople-appfiles/dist
    pm2 stop default
    pm2 start npm -- start --name main.js
