---
- name: "create directory for prometheus."
  become: true
  file:
    path: /etc/prometheus
    state: directory
    mode: "0777"

- name: "create directory for prometheus."
  become: true
  file:
    path: /var/lib/prometheus
    state: directory
    mode: "0777"

- name: "install Prometheus."
  unarchive:
    src: https://github.com/prometheus/prometheus/releases/download/v2.19.0/prometheus-2.19.0.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: "move prometheus binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/prometheus
    dest: /usr/local/bin/prometheus
    remote_src: yes
    mode: "0777"

- name: "move promtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: "0777"

- name: "move consoles binary to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/consoles
    dest: /etc/prometheus/consoles
    remote_src: yes
    mode: "0777"

- name: "move console_libraries binary to /etc/prometheus."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/console_libraries
    dest: /etc/prometheus/console_libraries
    remote_src: yes
    mode: "0777"

- name: "move promtool binary to /usr/local/bin."
  become: true
  copy:
    src: /tmp/prometheus-2.19.0.linux-amd64/promtool
    dest: /usr/local/bin/promtool
    remote_src: yes
    mode: "0777"

- name: "add prometheus.yml configuration."
  become: true
  copy:
    src: prometheus.yml
    dest: /etc/prometheus/

- name: "add prometheus.service configuration."
  become: true
  copy:
    src: prometheus.service
    dest: /etc/systemd/system/

- name: "change the permissions for prometheus files."
  become: true
  file:
    path: /etc/prometheus
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0777"
    recurse: yes
  loop:
    - /usr/local/bin/prometheus
    - /usr/local/bin/promtool
    - /etc/prometheus/consoles
    - /etc/prometheus/console_libraries
    - /var/lib/prometheus

- name: "enable prometheus service"
  become: true
  systemd:
    state: restarted
    daemon_reload: yes
    name: prometheus
    enabled: yes
