---
- name: "installing nodejs, npm"
  become: yes
  apt:
    pkg:
      - nodejs
      - npm

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
